version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./templates:/app/templates
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./ai_task_orchestra.db
    depends_on:
      - redis
    restart: unless-stopped
    command: uvicorn ai_task_orchestra.main:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./templates:/app/templates
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./ai_task_orchestra.db
    depends_on:
      - redis
    restart: unless-stopped
    command: celery -A ai_task_orchestra.worker.celery_app worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
